### PR TITLE
HYS_FE_ls_3 complete HW

### PR DESCRIPTION
**Pull request by Activine**

### CODE REVIEW

**Comment by savenkovao-ou** [comment]
image

**Comment by savenkovao-ou** [comment]
image

**Comment by savenkovao-ou** [comment]
image

**Comment by savenkovao-ou** [comment]
image

image

**Comment by savenkovao-ou** [comment]
image

**Comment by savenkovao-ou** [comment]
Should be cursor pointer on non active

image

**Comment by savenkovao-ou** [comment]
image
image

**Comment by savenkovao-ou** [comment]
Lacks bg-image
image

**Comment by savenkovao-ou** [comment]
Duplication. Consider using a single (I tend to generic one).
Check for other duplication places
image

**Comment by savenkovao-ou** [comment]
Consider using vars.
Consider checking for other duplication places
image
image

**Comment by savenkovao-ou** [comment]
Why gradient?

image
image

**Comment by savenkovao-ou** [comment]
missing bg image
image

**Comment by savenkovao-ou** [comment]
Maybe it's better to use max-width for these items?
image
image
image

**Comment by savenkovao-ou** [comment]
image

**Comment by savenkovao-ou** [comment]
Missing bg image
image

**Comment by savenkovao-ou** [comment]
Missing bg image
image
image

**Comment by savenkovao-ou** [comment]
As a suggestion: is it better to use center alignment on mobile?
Same for next block
image

**Comment by savenkovao-ou** [comment]
Consider providing similar wrapping/alignment behavior
image

**Comment by savenkovao-ou** [comment]
Would be nice to get rid of this white spaces
image

**Comment by Activine** [comment]
> 



> image
image

**Comment by Activine** [comment]
> image

image
I add Lorem in HTML and all work well. But when I add Lorem in Chrome dev tools code is broken.

**Comment by Activine** [comment]
> Missing bg image image

image
image
image
I don`t know why BG image is empty

**Comment by Activine** [comment]
> Maybe it's better to use max-width for these items? image image image

 I decide to use the display grid in this case. looks good.

**Comment by savenkovao** [comment]
> > image
> 
> image I add Lorem in HTML and all work well. But when I add Lorem in Chrome dev tools code is broken.

Because your Lorem test string has spaces, but 777777777777777777777777777 no

**Comment by savenkovao** [comment]
> > Missing bg image image
> 
> image image image I don`t know why BG image is empty

image

display: none

**Pull request merged**
